---


- name: install apache and httpd
  ansible.builtin.apt:
    name: apache2
    state: absent
    update_cache: true
- name: copy file to the given destination on all servers
  copy:
    src: index.html
    dest: ansible/html
    owner: root
    group: root
    mode: '0644'

- name: remove file to the given destination on all servers
  file:
    path: ansible/html
    state: absent