---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "public-compute-instance"
    #        vpc_subnet_id: subnet-5ca1ab1e
    instance_type: t2.micro
    security_group: default
    region: us-east-1
    aws_access_key: AKIASI7LSVTCOCZYL347
    aws_secret_key: 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

    network:
      assign_public_ip: true
    image_id: ami-0ec10929233384c7f
